# ----------------------------------------
# 配置
# ----------------------------------------
# ----------------------------------------
# quartz PROPERTIES
# ----------------------------------------
tp.quartz.enable=true
# ----------------------------------------
# log properties 日志
# ----------------------------------------
