<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies -->
    <parent>
        <groupId>com.lsnju.tp3</groupId>
        <artifactId>tp-base-dep</artifactId>
        <version>4.0.3-SNAPSHOT</version>
        <relativePath>../tp-base-dep</relativePath>
    </parent>
    <artifactId>tp-domain-jackson</artifactId>

    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>${project.artifactId}</description>
    <url>https://github.com/lsnju/tp-base</url>

    <properties>
        <skipTests>false</skipTests>
    </properties>

    <dependencies>

        <dependency>
            <groupId>com.lsnju.tp3</groupId>
            <artifactId>tp-utils</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/tools.jackson.core/jackson-databind -->
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

    </dependencies>

</project>
